- name: Michael Sarahan
  email: msarahan@gmail.com
  github: msarahan
  alternate_emails:
  - msarahan@continuum.io
  - msarahan@anaconda.com
  - msarahan@gmail.com
  aliases:
  - Mike Sarahan
  - Michael Sarahan
  num_commits: 194
  first_commit: 2019-01-03 20:00:40
- name: Nehal J Wani
  email: nehaljw.kkd1@gmail.com
  num_commits: 4
  first_commit: 2019-05-01 08:25:27
  github: nehaljwani
- name: Jonathan J. Helmus
  email: jjhelmus@gmail.com
  num_commits: 10
  first_commit: 2019-08-02 14:19:54
  github: jjhelmus
- name: Alan Du
  email: alanhdu@gmail.com
  num_commits: 4
  first_commit: 2019-11-07 05:49:27
  github: alanhdu
- name: Ray Donnelly
  email: mingw.android@gmail.com
  num_commits: 14
  first_commit: 2020-05-06 10:49:55
  github: mingwandroid
- name: Pure Software
  email: ossdev@puresoftware.com
  aliases:
  - ossdev07
  num_commits: 1
  first_commit: 2020-01-06 10:18:31
  github: ossdev07
- name: John Lee
  email: johnleenimh@gmail.com
  aliases:
  - leej3
  num_commits: 12
  first_commit: 2021-02-23 12:20:16
  github: leej3
- name: Matthew R. Becker
  email: beckermr@users.noreply.github.com
  num_commits: 2
  first_commit: 2020-12-29 14:58:11
  github: beckermr
- name: Eli Uriegas
  email: seemethere101@gmail.com
  num_commits: 1
  first_commit: 2021-03-14 08:41:18
  github: seemethere
- name: Daniel Bast
  email: 2790401+dbast@users.noreply.github.com
  num_commits: 2
  first_commit: 2021-04-12 11:49:45
  github: dbast
- name: Conda Bot
  email: 18747875+conda-bot@users.noreply.github.com
  num_commits: 26
  first_commit: 2022-01-17 20:22:29
  github: conda-bot
  aliases:
  - conda-bot
  - Distro Bot
  - distro-bot@anaconda.com
  - conda bot
  alternate_emails:
  - ad-team+condabot@anaconda.com
  - 18747875+conda-bot@users.noreply.github.com
  - Distro Bot
  - distro-bot@anaconda.com
- name: Cheng H. Lee
  email: clee@anaconda.com
  alternate_emails:
  - chenghlee@users.noreply.github.com
  num_commits: 4
  first_commit: 2022-02-09 18:08:33
- name: Chris Burr
  email: chrisburr@users.noreply.github.com
  num_commits: 1
  first_commit: 2022-02-17 10:23:53
- name: Daniel Holth
  email: dholth@anaconda.com
  num_commits: 12
  first_commit: 2021-08-20 21:11:50
  github: dholth
- name: Vadim Zayakin
  email: 77290357+vz-x@users.noreply.github.com
  aliases:
  - vz-x
  num_commits: 1
  first_commit: 2022-02-17 11:31:22
  github: vz-x
- name: Christopher Barber
  email: christopher.barber@analog.com
  num_commits: 2
  first_commit: 2022-02-09 01:00:38
- name: Jannis Leidel
  email: jannis@leidel.info
  num_commits: 9
  first_commit: 2021-09-17 21:51:27
  github: jezdez
- name: Tobias "Tobi" Koch
  email: tkoch@anaconda.com
  num_commits: 1
  first_commit: 2022-03-31 19:54:23
- name: Marius van Niekerk
  email: marius.v.niekerk@gmail.com
  num_commits: 1
  first_commit: 2022-07-19 15:55:18
  github: mariusvniekerk
- name: Ken Odegard
  email: kodegard@anaconda.com
  num_commits: 5
  first_commit: 2022-06-15 15:11:13
  github: kenodegard
