# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
python:
  - "2.7"
  - "3.7"

install:
  - wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-4.7.5-linux-64.exe -O conda.exe
  - chmod +x conda.exe
  - export CONDA_ALWAYS_YES=1
  - ./conda.exe create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda conda-build pytest six pytest-cov pytest-mock
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install futures;
    fi
  - conda build conda.recipe --no-test
  - conda install --use-local conda-package-handling
  - conda info -a
script:
  # rebuilding the recipe with our new CPH installed tests it a bit deeper than the test suite.
  - conda build conda.recipe
  - pytest -v --color=yes --cov=conda_package_handling tests
after_success:
  - conda install codecov
  - codecov
