{% set name = "conda-package-handling" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  - path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cph = conda_package_handling.cli:main

requirements:
  build:
    - python
    - pip
  host:
    - python
    - pip
  run:
    - python
    - tqdm
    - conda-package-streaming >=0.4.0

test:
  source_files:
    - tests
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  imports:
    - conda_package_handling
  commands:
    # This test is skipped until Dec 2019 which is weird. Skip for now.
    - pytest tests -k "not test_secure_refusal_to_extract_abs_paths"

about:
  home: https://github.com/conda/conda-package-handling
  dev_url: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Create and extract conda packages of various formats

extra:
  recipe-maintainers:
    - msarahan
    - beckermr
    - dbast
    - dholth