# libarchive 3.4.0 breaks some symlink stuff on macos.  Holding back for now.
{% set libarchive_version = "3.3.3" %}
{% set build_num = "5" %}

package:
  name: conda-package-handling
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  - path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: {{ build_num }}
  entry_points:
    - cph = conda_package_handling.cli:main
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - msinttypes  # [win and vc<14]
    - _libarchive_static_for_cph
  run:
    - futures   # [py27]
    - python
    - six
    - tqdm
test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
  imports:
    - conda_package_handling
    - conda_package_handling.archive_utils_cy
  commands:
    - pytest tests
about:
  home: https://github.com/conda/conda-package-handling
  summary: Create and extract conda packages of various formats
